import Head from 'next/head'
import MainBody from '../Compos/MainBody'
import MainFooter from '../Compos/MainFooter'
import MainHeader from '../Compos/MainHeader'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <MainHeader />
        <MainBody />
        <MainFooter />
      </main>
    </div>
  )
}
